### ISSUE TITLE
nvim-cmp new hl groups

### ISSUE THREAD

**Issue by ghost** [sainnhe/gruvbox-material#110]
nvim-cmp recently added the ability to customize the hl groups of lsp completion items in the menu.

https://github.com/hrsh7th/nvim-cmp#cmpitemkindkind_name

Gruvbox material can take advantage of these and make it closer to the VSCode version perhaps

here's an example from reddit: https://www.reddit.com/r/neovim/comments/r42njg/comment/hminxv3/?utm_source=share&utm_medium=web2x&context=3

**Comment by sainnhe** [comment]
I'm not a user of nvim-cmp, but I tried that, however I can't get the kind highlights to work, all the kind colors are still yellow on my machine.

I added the hi groups based on tree-sitter highlights, but I can't test it. Could you help me test the following code on your machine? Simply save the text as `highlights.diff` and execute `git apply /path/to/highlights.diff` in the directory of gruvbox-material.

```diff
diff --git a/colors/gruvbox-material.vim b/colors/gruvbox-material.vim
index 6550f8b..4ca5807 100644
--- a/colors/gruvbox-material.vim
+++ b/colors/gruvbox-material.vim
@@ -957,6 +957,31 @@ highlight! link CmpItemAbbr Fg
 highlight! link CmpItemAbbrDeprecated Fg
 highlight! link CmpItemMenu Fg
 highlight! link CmpItemKind Yellow
+highlight! link CompletionItemKindText Fg
+highlight! link CompletionItemKindMethod Green
+highlight! link CompletionItemKindFunction Green
+highlight! link CompletionItemKindConstructor Green
+highlight! link CompletionItemKindField Green
+highlight! link CompletionItemKindVariable Blue
+highlight! link CompletionItemKindClass Yellow
+highlight! link CompletionItemKindInterface Yellow
+highlight! link CompletionItemKindModule Yellow
+highlight! link CompletionItemKindProperty Blue
+highlight! link CompletionItemKindUnit Purple
+highlight! link CompletionItemKindValue Purple
+highlight! link CompletionItemKindEnum Yellow
+highlight! link CompletionItemKindKeyword Red
+highlight! link CompletionItemKindSnippet Aqua
+highlight! link CompletionItemKindColor Aqua
+highlight! link CompletionItemKindFile Aqua
+highlight! link CompletionItemKindReference Blue
+highlight! link CompletionItemKindFolder Aqua
+highlight! link CompletionItemKindEnumMember Blue
+highlight! link CompletionItemKindConstant Blue
+highlight! link CompletionItemKindStruct Yellow
+highlight! link CompletionItemKindEvent Orange
+highlight! link CompletionItemKindOperator Orange
+highlight! link CompletionItemKindTypeParameter Yellow
 " }}}
 " folke/trouble.nvim {{{
 highlight! link TroubleText Fg
```

**Comment by nghialm269** [comment]
> ```diff
> +highlight! link CompletionItemKindText Fg
> ```

Change `Completion` to `Cmp` works for me.

**Comment by sainnhe** [comment]
Done via https://github.com/sainnhe/gruvbox-material/commit/77d708e44d5351dc47d706bdb8fea1a518f226ce

**Comment by dathinaios** [comment]
This is still not working for me and this issue indicates that there are others that experience the same issue: https://github.com/hrsh7th/nvim-cmp/issues/832

Am I missing something maybe?

EDIT: I am indeed missing changing the `cmp` setting to `custom` instead of `native` 👍
